---
apiVersion: external-secrets.io/v1 # welke api versie van external secrets
kind: ExternalSecret # dit is een external secret resource, geen gewone k8s secret
metadata:
  name: tailscale-auth-key # naam van deze external secret in k8s
  namespace: tailscale # namespace waar deze external secret leeft
spec:
  refreshInterval: "1h" # hoe vaak ESO checkt of het secret in vault is veranderd
  secretStoreRef: 
    name: vault-secret-store # naam van clustersecretstore (brug naar vault) 
    kind: ClusterSecretStore # type store: cluster-wide, werkt in alle namespaces
  target:
    name: tailscale-auth # deze key komt in de k8s secret die ESO aanmaakt
                        # dit is wat cert-manager ziet als "existing secret" in de helm chart
  data:
  - secretKey: TS_AUTHKEY # key binnen k8s secret (wat app verwacht)
    remoteRef:
      key: tailscale/auth-key # pad in vault
      property: tailscale-auth-key # naam zoals je het in vault hebt aangemaakt
  