---
apiVersion: external-secrets.io/v1 # welke api versie van external secrets
kind: ExternalSecret # dit is een external secret resource, geen gewone k8s secret
metadata:
  name: grafana-admin # naam van deze external secret in k8s
  namespace: observability # namespace waar deze external secret leeft
spec:
  refreshInterval: "1h" # hoe vaak ESO checkt of het secret in vault is veranderd
  secretStoreRef: 
    name: vault-secret-store # naam van clustersecretstore (brug naar vault) 
    kind: ClusterSecretStore # type store: cluster-wide, werkt in alle namespaces
  target:
    name: grafana-admin # deze key komt in de k8s secret die ESO aanmaakt
                        # dit is wat grafana ziet als "existing secret" in de helm chart
  data:
  - secretKey: admin-user # key binnen k8s secret (wat app verwacht)
    remoteRef:
      key: grafana # pad in vault (kubernetes/grafana) waar ESO de waarde haalt
      property: admin-user # welke property binnen vault secret (grafana) moet worden gebruikt
  - secretKey: admin-password # tweede key in hetzelfde k8s secret
    remoteRef:
      key: grafana # zelfde vault pad als hierboven, maar nu halen we een andere property eruit
      property: admin-password # andere property binnen vault secret (grafana) die de admin password bevat