---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: drone-secret
  namespace: drone
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: drone-secret
  data:
  - secretKey: DRONE_GITLAB_CLIENT_ID        # eerste key in K8s secret
    remoteRef:
      key: drone/credentials
      property: DRONE_GITLAB_CLIENT_ID
  - secretKey: DRONE_GITLAB_CLIENT_SECRET    # tweede key, eigen blok
    remoteRef:
      key: drone/credentials
      property: DRONE_GITLAB_CLIENT_SECRET
  - secretKey: DRONE_RPC_SECRET              # derde key, eigen blok
    remoteRef:
      key: drone/credentials
      property: DRONE_RPC_SECRET
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: drone-registry-secret
  namespace: drone
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: drone-registry-secret
  data:
  - secretKey: REGISTRY_USERNAME
    remoteRef:
      key: drone/registry
      property: REGISTRY_USERNAME
  - secretKey: REGISTRY_PASSWORD
    remoteRef:
      key: drone/registry
      property: REGISTRY_PASSWORD