---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: test-secret
  namespace: vault
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: test-secret-k8s
  data:
  - secretKey: username
    remoteRef:
      key: test-secret
      property: username
  - secretKey: password
    remoteRef:
      key: test-secret
      property: password
